qr: mm_io.f90 HW3problem1.f90
	gfortran -c HW3problem1.f90 mm_io.f90 -g
	gfortran -o qr.exe HW3problem1.o mm_io.o -g
laplace: HW3problem2.f90
	gfortran -c HW3problem2.f90
	gfortran -o laplace.exe HW3problem2.o